### ISSUE TITLE
ps2-rw-speed elf file

### ISSUE THREAD

**Issue by Vyacheslav91** [rickgaiser/ps2-rw-speed#1]
Good afternoon. I need to test the smb speed on my ps2, but I can't seem to compile your code into an elf file. Tried on ps2toolchain and installed ps2sdk on linux. Nothing works. Can you help me?

**Comment by rickgaiser** [comment]
The latest source code can be found here:
https://gitlab.com/ps2max/testing/speed-testing

SMB code has not been tested in a long time, so it probably does not work anymore. I currently do not have time or interest to work on this testing tool, but if you know how to develop, then perhaps you can try?

You need to modify config.h for the things you would like to test / modules you need to load.
You also need to modify ee/main.c for connecting to your server IP/username/password.

My personal test results can be found here:
https://docs.google.com/spreadsheets/d/1FWeNMK-7yZoKl8DIHOQxzG5mf8BoS33jNnL1dF9dzRA/edit?usp=sharing

Another option for testing the speed of SMB is to use the OPL test iso. Download the iso, put it on your SMB share, and start the iso using OPL. You can find the iso here:
https://github.com/ps2homebrew/Open-PS2-Loader/actions/runs/4966690977

**Comment by Vyacheslav91** [comment]
Thank you very much for your help! I just need a test. I myself am a programmer, but I do not know how to work with ps2 architecture. I can change the data in the code, but I can’t compile, it gives a lot of errors. But I will try OPLTESTISO, maybe this is what I need!

**Comment by Vyacheslav91** [comment]
and you don't have ready elf files left?

**Comment by rickgaiser** [comment]
You're welcome. No, I don't have ready elf files.
